engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "codesize,design,unusedcode"
exclude_paths:
  - tests/**/*
  - vendor/**/*
ratings:
  paths:
    - "**.php"
    - "**.module"
    - "**.inc"